# To create the conda env:
#  $ conda env create -p /path/to/env/gatiab-dev -f "environment.yml
#  $ conda activate gatiab-dev
#
name: gatiab-dev
channels:
 - conda-forge
 - defaults
dependencies:
  - python<3.12
  - numpy>=1.26.4
  - xarray>=2024.7.0
  - scipy>=1.13.1
  - tqdm>=4.66.5
  - pytest>=8.3.2
